apiVersion: v1
kind: Service
metadata:
  name: front-app-service
spec:
  type: NodePort
  selector:
    app: front-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000

