name: project-ci
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: "Build base image"
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          DOCKER_USER=mdnfiras
          FRONT_IMG_TAG=$(sha256sum package.json | cut -c1-15 )
          RES=$(curl -u mdnfiras:$DOCKER_TOKEN https://registry.hub.docker.com/v2/repositories/$DOCKER_USER/base-front/tags | { grep $FRONT_IMG_TAG || true; } )
          if [ -z "$RES" ]; then
            echo "Did not find image with tag $FRONT_IMG_TAG"
            docker login -u $DOCKER_USER -p $DOCKER_TOKEN
            docker build -f base.Dockerfile -t $DOCKER_USER/base-front:$FRONT_IMG_TAG .
            docker push $DOCKER_USER/base-front:$FRONT_IMG_TAG
            docker tag $DOCKER_USER/base-front:$FRONT_IMG_TAG $DOCKER_USER/base-front:latest
            docker push $DOCKER_USER/base-front:latest
            docker logout
          else
            echo "Found image with tag $FRONT_IMG_TAG"
          fi
          
      - name: "Build and containerize app"
        run: |
          DOCKER_USER=mdnfiras
          docker pull $DOCKER_USER/base-front:latest
          docker tag $DOCKER_USER/base-front:latest base-front:latest
          docker build -t front-app .
          
      - name: "Test containerized app"
        run: |
          docker run -d -p 80:80 --name my-app front-app
          sleep 5
          docker ps --all
          docker logs my-app
          curl localhost
          docker stop my-app

      - name: "Push containerized app"
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          DOCKER_USER=mdnfiras
          docker login -u $DOCKER_USER -p $DOCKER_TOKEN
          docker tag front-app $DOCKER_USER/front-app:$GITHUB_RUN_NUMBER
          docker push $DOCKER_USER/front-app:$GITHUB_RUN_NUMBER
          docker tag $DOCKER_USER/front-app:$GITHUB_RUN_NUMBER $DOCKER_USER/front-app:latest
          docker push $DOCKER_USER/front-app:latest
          docker logout
