name: project-ci
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: "Build base image"
        run: docker build -t base-front -f base.Dockerfile .
          
      - name: "Build and containerize app"
        run: docker build -t front-app .
          
      - name: "Test containerized app"
        run: |
          docker run -d -p 80:80 --name my-app front-app
          sleep 5
          docker ps --all
          docker logs my-app
          curl localhost
          docker stop my-app
