name: project-ci
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: ci_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build -t base-front -f base.Dockerfile .
          docker build -t front-app .
          docker run --name my-app -p 80:80 front-app
          curl localhost
          docker stop my-app
          
